version: 2

sources:
  - name: jaffle_shop
    schema: jaffle_shop
    database: raw
    
    tables:
      - name: customers
        columns:
          - name: id
            data_tests:
              - not_null
              - unique
        
      - name: jaffle_shop_orders
        identifier: orders
        description: One record per order
        
        config:
          loaded_at_field: _etl_loaded_at
          freshness:
            warn_after:
              count: 10
              period: day
            error_after:
              count: 10000
              period: hour